{% set name = "swagger-ui-bundle" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/swagger_ui_bundle-{{ version }}.tar.gz
  sha256: 20673c3431c8733d5d1615ecf79d9acf30cff75202acaf21a7d9c7f489714529

build:
  number: 0
  skip: true  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed --no-cache-dir -vv

requirements:
  host:
    - python
    - pip
    - poetry-core >=1.2.0
  run:
    - python
    - jinja2 >=3.0.0,<4.0.0
    - importlib_resources >=5.7.1,<6.0.0 # [py<39]

test:
  imports:
    - swagger_ui_bundle
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/dtkav/swagger_ui_bundle
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: swagger_ui_bundle - swagger-ui files in a pip package
  description: |
    This package contains the static files for swagger-ui as a python package.
  dev_url: https://github.com/dtkav/swagger_ui_bundle
  doc_url: https://github.com/dtkav/swagger_ui_bundle/blob/master/README.rst

extra:
  recipe-maintainers:
    - msarahan
